-- ============================================================================
-- ACBB TT — refonte 2026/27 : tables du guichet serveur (fonction Edge `api`)
-- ----------------------------------------------------------------------------
-- Idempotent : rejouable sans risque (create ... if not exists partout).
-- RLS activée sur chaque table SANS aucune policy : ni la clé publique ni un
-- utilisateur authentifié ne peuvent lire/écrire. Seule la fonction `api`
-- (clé service_role, qui contourne la RLS) accède à ces tables.
-- Exécution : scripts/refonte_deploy.sh (API de gestion Supabase).
-- ============================================================================

-- ─── liens : jetons d'accès capitaine / sportive ─────────────────────────────
-- Le jeton brut n'est JAMAIS stocké : token_hash = sha256(PEPPER ':' jeton).
create table if not exists public.liens (
  id           bigint generated by default as identity primary key,
  token_hash   text        not null unique,
  role         text        not null check (role in ('capitaine', 'sportive')),
  equipe       text,                          -- 'M6', 'F2'… (null pour la sportive)
  nom          text        not null,          -- nom affiché du porteur du lien
  actif        boolean     not null default true,
  created_at   timestamptz not null default now(),
  last_used_at timestamptz
);
create index if not exists liens_actif_role_idx on public.liens (actif, role, equipe);
comment on table public.liens is 'Liens uniques (#t=<jeton>) des capitaines et de la sportive. Jeton stocké haché (PEPPER), jamais en clair.';

-- ─── naissances : date de naissance hachée par licence ───────────────────────
-- hash = sha256(PEPPER ':' licence ':' AAAA-MM-JJ). Jamais de date en clair.
-- source 'fichier' (inscriptions officielles) l'emporte sur 'saisie' (1re saisie du joueur).
create table if not exists public.naissances (
  licence    text        primary key,
  hash       text        not null,
  source     text        not null check (source in ('fichier', 'saisie')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.naissances is 'Hachés des dates de naissance (contrôle d''identité joueur). source=fichier fait foi sur saisie.';

-- ─── tentatives : rate limit des entrées joueur ──────────────────────────────
-- 5 échecs / IP / 10 min, 3 échecs / licence / heure (calculé dans la fonction).
create table if not exists public.tentatives (
  id      bigint generated by default as identity primary key,
  ip      text,
  licence text,
  ok      boolean     not null default false,
  at      timestamptz not null default now()
);
create index if not exists tentatives_ip_at_idx      on public.tentatives (ip, at desc);
create index if not exists tentatives_licence_at_idx on public.tentatives (licence, at desc);
comment on table public.tentatives is 'Journal des tentatives d''entrée joueur (licence + date). Purge possible au-delà de 30 jours.';

-- ─── appareils : au plus 3 licences distinctes par appareil (x-acbb-device) ──
create table if not exists public.appareils (
  device_id text        not null,
  licence   text        not null,
  first_at  timestamptz not null default now(),
  primary key (device_id, licence)
);
comment on table public.appareils is 'Couples (appareil, licence) vus à l''entrée joueur : limite 3 licences par appareil.';

-- ─── debriefs_log : comptes rendus de match des capitaines (append + validation)
-- La dernière ligne par (equipe, journee) fait foi côté capitaine ;
-- la sportive complète la ligne (texte_corrige / texte_final / publie…).
create table if not exists public.debriefs_log (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),
  equipe           text        not null,
  journee          int         not null check (journee between 1 and 30),
  auteur           text,                       -- nom du lien capitaine
  score_acbb       int         check (score_acbb is null or score_acbb between 0 and 50),
  score_adv        int         check (score_adv  is null or score_adv  between 0 and 50),
  texte            text,                       -- texte brut du capitaine
  texte_corrige    text,                       -- proposition IA (orthographe uniquement)
  texte_final      text,                       -- texte validé par la sportive
  photo_path       text,                       -- chemin dans le bucket privé `debriefs`
  photo_public_url text,                       -- URL dans le bucket public `debriefs-publies` (après publication)
  visible_club     boolean     not null default true,
  publie           boolean     not null default false,
  publie_par       text,
  publie_at        timestamptz,
  renvoye_message  text                        -- message de la sportive au capitaine (demande de retouche)
);
create index if not exists debriefs_log_equipe_journee_idx on public.debriefs_log (equipe, journee, id desc);
create index if not exists debriefs_log_journee_idx        on public.debriefs_log (journee, id desc);
comment on table public.debriefs_log is 'Debriefs de match : scores + texte + photo, saisis par le capitaine, publiés par la sportive.';

-- ─── journal : toute écriture passe ici (traçabilité) ────────────────────────
create table if not exists public.journal (
  id      bigint generated by default as identity primary key,
  at      timestamptz not null default now(),
  acteur  text,                                -- nom du lien, ou « Prénom Nom (joueur) »
  role    text,                                -- 'joueur' | 'capitaine' | 'sportive'
  action  text        not null,
  details jsonb
);
create index if not exists journal_at_idx     on public.journal (at desc);
create index if not exists journal_action_idx on public.journal (action, at desc);
comment on table public.journal is 'Journal d''audit des écritures effectuées via la fonction api.';

-- ─── RLS sans policy : verrou total pour tout ce qui n'est pas service_role ──
alter table public.liens        enable row level security;
alter table public.naissances   enable row level security;
alter table public.tentatives   enable row level security;
alter table public.appareils    enable row level security;
alter table public.debriefs_log enable row level security;
alter table public.journal      enable row level security;

-- Ceinture + bretelles : on retire aussi les droits implicites des rôles API.
revoke all on table public.liens, public.naissances, public.tentatives,
              public.appareils, public.debriefs_log, public.journal
  from anon, authenticated;
